export const tokens = {
  colors: {
    background: {
      primary: '#0A1412',
      secondary: '#0F1F1A',
    },
    card: {
      base: '#0F1F1A',
      elevated: '#132923',
      hover: '#18352D',
      active: '#1C3D35',
    },
    sidebar: {
      bg: '#08120F',
    },
    primary: {
      main: '#22C55E',
      hover: '#16A34A',
      light: '#4ADE80',
      glow: 'rgba(34,197,94,0.25)',
    },
    ai: {
      accent: '#22D3EE',
      teal: '#14B8A6',
    },
    text: {
      lightBg: {
        primary: '#ECFDF5',
        secondary: '#A7F3D0',
        muted: '#6EE7B7',
      },
      darkBg: {
        primary: '#ECFDF5',
        secondary: '#A7F3D0',
        muted: '#6EE7B7',
      },
    },
    border: {
      light: '#2A4D40',
      dark: '#1F3D35',
    },
    status: {
      success: '#16A34A',
      warning: '#F59E0B',
      error: '#DC2626',
      info: '#0EA5E9',
    },
  },
  spacing: {
    px: '1px',
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '20px',
    6: '24px',
    7: '32px',
    8: '40px',
    9: '48px',
    10: '64px',
  },
  radii: {
    sm: '7px',
    md: '8px',
    lg: '10px',
    xl: '12px',
    pill: '999px',
  },
  shadows: {
    soft: '0 4px 12px rgba(0, 0, 0, 0.05)',
    elevated: '0 8px 24px rgba(0, 0, 0, 0.25)',
    glow: '0 0 12px rgba(34, 197, 94, 0.18)',
    innerDepth: 'inset -1px 0 0 var(--surface)',
    card: '0 18px 44px rgba(7, 18, 15, 0.22)',
    cardHover: '0 22px 56px rgba(7, 18, 15, 0.28)',
  },
  transitions: {
    smooth: 'all 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
    fast: 'all 0.15s ease-out',
  },
  layout: {
    sidebar: '218px',
    topbar: '54px',
    contentMax: '1400px',
  },
};

export const dashboardCssVars = {
  '--bg': tokens.colors.background.primary,
  '--bg-secondary': tokens.colors.background.secondary,
  '--card': tokens.colors.card.base,
  '--card-elevated': tokens.colors.card.elevated,
  '--card-hover': tokens.colors.card.hover,
  '--card-active': tokens.colors.card.active,
  '--primary': tokens.colors.primary.main,
  '--primary-hover': tokens.colors.primary.hover,
  '--primary-light': tokens.colors.primary.light,
  '--primary-glow': tokens.colors.primary.glow,
  '--ai-accent': tokens.colors.ai.accent,
  '--ai-teal': tokens.colors.ai.teal,
  '--text-primary': tokens.colors.text.lightBg.primary,
  '--text-secondary': tokens.colors.text.lightBg.secondary,
  '--text-muted': tokens.colors.text.lightBg.muted,
  '--text-dark-primary': tokens.colors.text.darkBg.primary,
  '--text-dark-secondary': tokens.colors.text.darkBg.secondary,
  '--text-dark-muted': tokens.colors.text.darkBg.muted,
  '--border-light': tokens.colors.border.light,
  '--border-dark': tokens.colors.border.dark,
  '--success': tokens.colors.status.success,
  '--warning': tokens.colors.status.warning,
  '--error': tokens.colors.status.error,
  '--info': tokens.colors.status.info,
  '--space-1': tokens.spacing[2],
  '--space-2': tokens.spacing[4],
  '--space-3': tokens.spacing[6],
  '--space-4': tokens.spacing[7],
  '--radius-sm': tokens.radii.md,
  '--radius-md': tokens.radii.lg,
  '--radius-lg': tokens.radii.xl,
  '--shadow-soft': tokens.shadows.soft,
  '--shadow-elevated': tokens.shadows.elevated,
  '--shadow-card': tokens.shadows.card,
  '--shadow-card-hover': tokens.shadows.cardHover,
  '--shadow-glow': tokens.shadows.glow,
  '--transition-fast': tokens.transitions.fast,
  '--transition-smooth': tokens.transitions.smooth,
  '--sidebar-width': tokens.layout.sidebar,
  '--topbar-height': tokens.layout.topbar,
  '--content-max': tokens.layout.contentMax,
};
